feature(basic files): w/example cmds
telicent-oss/telicent-frontend-cli pull request #1
Opened 2024-04-03 17:48 UTC by ACoolmanTelicent

Essentially the initial commit

2024-04-04 08:45 UTC, procolecato reviewed
Thanks for inviting me to review this repo's documentation.

It's a good start and I think most of my comments are probably due to this being early days for the repo's documentation.  For example I've commented that usage should be more than just typing "TEFE help".  But if there are no commands to use right now then I can understand why this might be a placeholder.

Some of my comments might also be down to my inexperience with modern development techniques.  For example I wasn't sure how to apply TEFE to a particular frontend repo.

It might be helpful to state who the intended audience is, e.g. all developers of frontend components.  And would that be all frontend developers in the world or just Telicent developers?

2024-04-04 08:50 UTC, ACoolmanTelicent commented on LICENSE
> +   Copyright 2024 Telicent Ltd.
hahaha, I'm so reminded of [this scene from the Good Place™](https://www.youtube.com/watch?v=etJ6RmMPGko)

2024-04-04 09:29 UTC, ACoolmanTelicent commented on README.md
> +CLI utility help frontend repos stay aligned, and easy to work with.
> How will it do this? Will it wrap-up and automate the scripts and checks described in the following paragraph?

Yep

> Is it used standalone as a CLI tool and / or is it linked into a package?

Yes both

2024-04-04 09:36 UTC, ACoolmanTelicent commented on README.md
> +To list available commands
Sure. Hm, Ok I'll probably pop the help strings directly into the readme.

Small Note: This project doesn't actually do anything yet

2024-04-04 11:50 UTC, procolecato commented on README.md
> +  <summary>To use (and develop) commands locally:</summary>
Ah, OK, thanks for the clarification I think that makes sense now.

You can use the TEFE CLI 'out of the box'.  This is what the wider README is describing.

OR 

If the standard TEFE CLI doesn't support what you want it to do you can develop new commands locally.  This is what the <details> section is describing.  As well as how to then use those new commands.

2024-04-04 11:52 UTC, procolecato commented on README.md
> +To list available commands
That's good to synchronise the help strings with the README!  

As mentioned, I did wonder if the emptiness of this section was simply due to the fact the project doesn't do anything yet.

2024-04-04 13:51 UTC, ACoolmanTelicent commented
@procolecato  Did some quick tweaks 

Admittedly I didn't _carefully_ go through all input with a fine tooth comb, but maybe its enough

2024-04-04 14:17 UTC, procolecato approved these changes
That's great, Ash!  Given this is at an early stage of development of the CLI it's looking really good.

I like how you've given a bit more context around what it's for, who it's for and intended usage.

It's also good to see the link to the general process for developing CLI tools.

I think it's a good structure and starting point as the CLI develops.

As you've suggested on PRs for other repositories, I'll tweak the odd typos I've spotted myself in a separate PR.

2024-04-10 09:11 UTC, ACoolmanTelicent commented
I regret not writing this in TS.

2024-04-10 14:33 UTC, dptelicent commented on README.md
> +# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
As this is in the install section, shouldn't the suggestion if using Yarn be `yarn add @telicent-oss/telicent-frontend-cli`?

2024-04-17 10:21 UTC, ACoolmanTelicent commented on README.md
> +# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
Gonna presume we are a "yarn shop", we don't "support" npm

2024-04-17 16:21 UTC, ACoolmanTelicent commented on dist/autoupdate.d.ts
> +export {};
Ignore `./dist`

2024-04-19 09:42 UTC, davec504 requested changes
If you are adding the dist folder gitignore then the dist folder should be removed from this commit

2024-04-19 09:45 UTC, davec504 commented
> If you are adding the dist folder gitignore then the dist folder should be removed from this commit

After chat with @ACoolmanTelicent this is intentional, allowing the CLI to be node 16 compliant

2024-04-19 10:20 UTC, davec504 requested changes

2024-04-19 10:20 UTC, davec504 commented on src/info/utils/checkNpmContext.test.js
> +  it.only("handles not being in an npm package", () => {
```suggestion
it("handles not being in an npm package", () => {
```

2024-04-19 10:20 UTC, davec504 commented on src/info/utils/checkNpmContext.ts
> +import * as fs from "fs";
```suggestion
import fs from "fs";
```

2024-04-19 10:20 UTC, davec504 commented on src/autoupdate.ts
> +updateNotifier.default({ pkg }).notify();
```suggestion
import updateNotifier from "update-notifier";
import fs from 'fs';
const pkg = JSON.parse(`${fs.readFileSync('./package.json')}`);
updateNotifier({ pkg }).notify();
```

2024-04-19 10:20 UTC, davec504 commented on src/utils/formatJsonFile.ts
> +import * as fs from "fs";
```suggestion
import util from "util";
import fs from "fs";
```

2024-04-19 10:20 UTC, davec504 commented on src/utils/tefe.config.json.utils.ts
> +import * as fs from "fs";
```suggestion
import fs from "fs";
```

2024-04-19 16:39 UTC, AlecsMissangu submitted a review, later dismissed

2024-04-22 08:14 UTC, dptelicent commented on README.md
> +# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
```
# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
```
👍🏻 Shouldn't the above comment be changed in that case, and maybe the default tefe command?

2024-04-25 08:35 UTC, davec504 approved these changes

2024-04-25 08:35 UTC, davec504 commented on src/noise/index.ts
> +const noise:(...args: any[]) => void = (options) => {
Is this an easter egg or a template that has just been left in?

2024-04-25 08:37 UTC, ACoolmanTelicent commented on src/noise/index.ts
> +const noise:(...args: any[]) => void = (options) => {
I didn't mean to, but i figured I'll leave it in as a simple example for a while

2024-04-25 14:44 UTC, AlecsMissangu submitted a review, later dismissed

2024-04-26 10:06 UTC, dptelicent submitted a review, later dismissed

2024-04-26 10:06 UTC, dptelicent commented on src/utils/tefe.config.json.utils.test.js
> +        `Can not create already existing: ${TEFE_CONFIG}`
```suggestion
        `Cannot create already existing: ${TEFE_CONFIG}`
```

2024-04-26 10:06 UTC, dptelicent commented on src/utils/tefe.config.json.utils.ts
> +    throw Error(`Can not create already existing: ${TEFE_CONFIG}`);
```suggestion
    throw Error(`Cannot create already existing: ${TEFE_CONFIG}`);
```

2024-04-26 10:06 UTC, dptelicent commented on README.md
> +tefe version # or `yarn tefe version`
**Optional suggestion**
As Yarn is the default.

2024-04-26 10:07 UTC, dptelicent commented on README.md
> +# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
See https://github.com/telicent-oss/telicent-frontend-cli/pull/1#discussion_r1580765385.

2024-04-26 11:00 UTC, ACoolmanTelicent commented on README.md
> +# IMPORTANT: If you use `yarn` to install locally, manually prefix with "yarn" e.g. `yarn tefe`
[6ab1614](https://github.com/telicent-oss/telicent-frontend-cli/pull/1/commits/6ab1614456c68c6ca1ca1ea458aa8f9cdfd0534c)

2024-04-26 12:02 UTC, davec504 approved these changes

2024-04-26 12:04 UTC, dptelicent approved these changes

2024-04-26 12:10 UTC, merged